# Generated by Django 4.0.3 on 2022-03-21 06:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
