# Generated by Django 4.0.3 on 2022-03-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alter_business_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date']},
        ),
    ]
