# Generated by Django 4.0.3 on 2022-03-22 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
